<a href="https://colab.research.google.com/github/matiasnr96/cloud-provider-analytics/blob/main/notebooks/01_exploracion_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from pathlib import Path

LANDING_PATH = Path("/content/drive/MyDrive/cloud-provider-analytics-data/landing")

print(LANDING_PATH)

/content/drive/MyDrive/cloud-provider-analytics-data/landing

In [4]:
import pandas as pd

customers = pd.read_csv(LANDING_PATH / "customers_orgs.csv")

customers.head()

,org_id,org_name,industry,hq_region,plan_tier,is_enterprise,signup_date,sales_rep,lifecycle_stage,marketing_source,nps_score
0,org_xaji0y6d,Nimbus Labs 0,Education,sa-east,standard,True,2025-05-26,rep_c,churned,partner,NaN
1,org_pbhsahxt,Nova Tech 1,Education,us-east,standard,False,2025-06-16,rep_d,lead,event,-3.0
2,org_hv3a3zmf,Gamma Data 2,Media,eu-central,pro,True,2025-05-12,rep_c,active,organic,4.0
3,org_8mdd4v30,Apex Data 3,Manufacturing,sa-east,standard,False,2025-05-30,rep_b,active,ads,12.0
4,org_t9nt3w5u,Delta Digital 4,E-commerce,us-west,standard,False,2025-05-16,rep_d,active,partner,17.0

## 1. Customers / Organizations

El archivo `customers_orgs.csv` contiene información de las organizaciones o clientes del proveedor cloud.

En esta primera exploración se analizarán:
- dimensiones del dataset;
- columnas disponibles;
- tipos de datos;
- valores nulos;
- valores únicos;
- posibles problemas de calidad.

In [6]:
print("Cantidad de filas:", customers.shape[0])
print("Cantidad de columnas:", customers.shape[1])

Cantidad de filas: 80
Cantidad de columnas: 11

In [7]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   org_id            80 non-null     object
 1   org_name          80 non-null     object
 2   industry          80 non-null     object
 3   hq_region         80 non-null     object
 4   plan_tier         80 non-null     object
 5   is_enterprise     80 non-null     bool
 6   signup_date       80 non-null     object
 7   sales_rep         80 non-null     object
 8   lifecycle_stage   80 non-null     object
 9   marketing_source  80 non-null     object
 10  nps_score         69 non-null     float64
dtypes: bool(1), float64(1), object(9)
memory usage: 6.5+ KB

In [8]:
customers.dtypes

org_id               object
org_name             object
industry             object
hq_region            object
plan_tier            object
is_enterprise          bool
signup_date          object
sales_rep            object
lifecycle_stage      object
marketing_source     object
nps_score           float64
dtype: object

In [9]:
customers.isnull().sum()

org_id               0
org_name             0
industry             0
hq_region            0
plan_tier            0
is_enterprise        0
signup_date          0
sales_rep            0
lifecycle_stage      0
marketing_source     0
nps_score           11
dtype: int64

In [10]:
print("Filas duplicadas:", customers.duplicated().sum())
print("org_id duplicados:", customers["org_id"].duplicated().sum())

Filas duplicadas: 0
org_id duplicados: 0

In [11]:
customers["org_id"].duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
75    False
76    False
77    False
78    False
79    False
Name: org_id, Length: 80, dtype: bool